[package]
name = "hycore"
version = "0.1.0"
edition = "2024"

[dependencies]
hyinstr.workspace = true
uuid.workspace = true
petgraph.workspace = true
smallvec.workspace = true
strum = { workspace = true, features = ["derive"] }
bitflags = { workspace = true }
nalgebra = { workspace = true, features = ["sparse"] }
enum-map = { workspace = true }
log = { workspace = true }
either.workspace = true
anyhow = { workspace = true }
bit-set = { workspace = true }

[features]
default = []
test-utils = []
