[package]
name = "hyinstr"
version = "0.1.2"
edition = "2024"

[dependencies]
uuid = { workspace = true }
strum = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "uuid/serde"]
