[workspace]
resolver = "2"
members = ["hyinstr"]

[workspace.dependencies]
smallvec = ">=0.6.10, <=1.15.1"
strum = ">=0.25.0"
either = "*"
termcolor = "^1.1.1"
pretty = ">=0.10"
term_size = "*"
chumsky = ">=0.11"
typed-arena = "*"
stackalloc = "^1.1.1"
clap = ">=4.0"
serde = "^1"
uuid = "^1"
parking_lot = "^0.12"
log = ">=0.2"

criterion = "0.5"
rand = "0.9.2"
rand_chacha = "0.9.0"
