[package]
name = "hyformal"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/HyperionProject/hyformal"
edition = "2024"
readme = "README.md"
description = "A formal, symbolic engine for hyperion"
keywords = ["formal", "symbolic", "hyperion"]
authors = ["Guillaume Boy√© <guillaume.boye@epfl.ch>"]

[dependencies]
smallvec = ">1.12"
strum = { version = ">0.26", features = ["derive"] }
pretty = { version = ">=0.12.5", features = ["termcolor"] }
termcolor = ">=1.4"
term_size = "0.3.2"
