[package]
name = "hyformal"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/HyperionProject/hyformal"
edition = "2024"
readme = "README.md"
description = "A formal, symbolic engine for hyperion"
keywords = ["formal", "symbolic", "hyperion"]
authors = ["Guillaume Boy√© <guillaume.boye@epfl.ch>"]

[dependencies]
smallvec = ">1.12"
strum = { version = ">0.26", features = ["derive"] }
pretty = { version = ">=0.12.5", features = ["termcolor"] }
termcolor = ">=1"
term_size = ">=0.3"
chumsky = ">=0.11"
typed-arena = ">=2.0"
bytemuck = ">=1.20.0"
stackalloc = "1.2.1"

[dev-dependencies]
clap = { version = ">=4.0", features = ["derive"] }

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "parser"
path = "examples/parser.rs"
