[workspace]
resolver = "2"
members = ["hyformal"]

[workspace.dependencies]
smallvec = "^1"
strum = { version = ">=0.26", features = ["derive"] }
either = ">=1"
termcolor = "^1"
pretty = { version = "^0.12", features = ["termcolor"] }
term_size = ">=0.3"
chumsky = ">=0.11"
typed-arena = "^2"
stackalloc = "^1"
clap = ">=4.0"
