[workspace]
resolver = "2"
members = ["hyformal"]

[workspace.dependencies]
smallvec = ">=0.6.10, <=1.15.1"
strum = { version = ">=0.25.0", features = ["derive"] }
either = "*"
termcolor = "^1.1.1"
pretty = { version = ">=0.10", features = ["termcolor"] }
term_size = "*"
chumsky = ">=0.11"
typed-arena = "*"
stackalloc = "^1.1.1"
clap = ">=4.0"
