[package]
name = "hycore-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
hyinstr = { workspace = true, features = ["chumsky"] }
hycore = { workspace = true, features = [] }
petgraph.workspace = true
uuid = { workspace = true, features = ["v4"] }
