[build-system]
requires = ["maturin>=1.11,<2.0"]
build-backend = "maturin"

[project]
name = "hypi"
requires-python = ">=3.8"
dynamic = ["version"]
license-files = ["LICENSE"]

[tool.maturin]
python-source = "python"
module-name = "hypi._sys"
